### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mistic100** [mistic100/Photo-Sphere-Viewer#1]
- [x] Better mousewheel support (see https://developer.mozilla.org/en-US/docs/Web/Events/wheel)
- [x] Default FOV & position JeremyHeleine/Photo-Sphere-Viewer#2
- [x] CSS classes to DOM elements
- [x] center loading image
