### ISSUE TITLE
TODO documentation

### ISSUE THREAD

**Issue by mistic100** [mistic100/Photo-Sphere-Viewer#727]
- [ ] display [attributions](https://github.com/mistic100/photo-sphere-viewer-data#attribution) somewhere
- [ ] add demo of custom pano data
- [x] add demo of overlay
